package com.nova.audify;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.Dialog;
import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Build;
import android.os.Handler;
import android.os.Looper;
import android.text.TextUtils;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.view.WindowManager;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.lang.ref.WeakReference;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicInteger;

final class AudifyInstantAlbums {
    private static final String SERVICE="com.nova.audify.AudifyPlaybackService",TAG="AUDIFY_INSTANT_ALBUMS_V681255",PILL=TAG+"_PILL",LABEL=TAG+"_LABEL",COVER=TAG+"_COVER",DISC=TAG+"_DISC";
    private static final Handler MAIN=new Handler(Looper.getMainLooper());
    private static final ExecutorService DETECT=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"AudifyAlbumDetect");t.setDaemon(true);return t;});
    private static final AtomicInteger GEN=new AtomicInteger();
    private static WeakReference<Activity> active=new WeakReference<>(null),scheduled=new WeakReference<>(null);
    private static volatile String observed="",albumFor="";
    private static volatile AudifyInstantAlbumMetadata.Album current;
    static final class Snap {String id="",title="",artist="",thumb="";}
    static void attach(Activity a){if(a==null)return;active=new WeakReference<>(a);install(a);poll(a);if(scheduled.get()!=a){scheduled=new WeakReference<>(a);schedule(a);}}
    private static void install(Activity a){View c=a.findViewById(android.R.id.content);if(!(c instanceof ViewGroup))return;ViewGroup root=(ViewGroup)c;if(root.findViewWithTag(PILL)!=null)return;FrameLayout host;if(root instanceof FrameLayout)host=(FrameLayout)root;else{host=new FrameLayout(a);root.addView(host,new ViewGroup.LayoutParams(-1,-1));}
        DiscButton disc=new DiscButton(a);disc.setTag(DISC);disc.setContentDescription("Ouvrir l’album");GradientDrawable db=new GradientDrawable();db.setShape(GradientDrawable.OVAL);db.setColor(Color.argb(210,12,17,24));db.setStroke(dp(a,1),Color.argb(220,168,255,63));disc.setBackground(db);disc.setAlpha(.82f);disc.setOnClickListener(v->{Snap s=snap();if(current!=null&&key(s).equals(albumFor))showAlbum(a,current,s);else if(!TextUtils.isEmpty(s.title))detect(a,s,true);});FrameLayout.LayoutParams dl=new FrameLayout.LayoutParams(dp(a,40),dp(a,40),Gravity.TOP|Gravity.END);dl.topMargin=dp(a,198);dl.rightMargin=dp(a,18);host.addView(disc,dl);
        LinearLayout pill=new LinearLayout(a);pill.setTag(PILL);pill.setOrientation(LinearLayout.HORIZONTAL);pill.setGravity(Gravity.CENTER_VERTICAL);pill.setPadding(dp(a,7),dp(a,6),dp(a,12),dp(a,6));pill.setElevation(dp(a,10));pill.setVisibility(View.GONE);pill.setAlpha(0);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.argb(238,10,14,20));bg.setCornerRadius(dp(a,18));bg.setStroke(dp(a,1),Color.argb(205,168,255,63));pill.setBackground(bg);
        ImageView art=new ImageView(a);art.setTag(COVER);art.setScaleType(ImageView.ScaleType.CENTER_CROP);GradientDrawable ph=new GradientDrawable();ph.setColor(Color.rgb(27,34,44));ph.setCornerRadius(dp(a,11));art.setBackground(ph);pill.addView(art,new LinearLayout.LayoutParams(dp(a,48),dp(a,48)));
        TextView label=text(a,"",15,Color.WHITE,true);label.setTag(LABEL);label.setSingleLine(true);label.setEllipsize(TextUtils.TruncateAt.END);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.leftMargin=dp(a,12);pill.addView(label,lp);TextView che=text(a,"›",25,Color.rgb(168,255,63),false);che.setGravity(Gravity.CENTER);pill.addView(che,new LinearLayout.LayoutParams(dp(a,24),dp(a,44)));pill.setOnClickListener(v->{if(current!=null)showAlbum(a,current,snap());});FrameLayout.LayoutParams pl=new FrameLayout.LayoutParams(-1,dp(a,62),Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);pl.leftMargin=dp(a,16);pl.rightMargin=dp(a,16);pl.bottomMargin=dp(a,180);host.addView(pill,pl);
    }
    private static void schedule(Activity a){WeakReference<Activity> ref=new WeakReference<>(a);MAIN.postDelayed(new Runnable(){public void run(){Activity x=ref.get();if(x==null||x.isFinishing()||(Build.VERSION.SDK_INT>=17&&x.isDestroyed())||active.get()!=x)return;poll(x);MAIN.postDelayed(this,1500);}},1000);}
    private static void poll(Activity a){Snap s=snap();String k=key(s);if(TextUtils.isEmpty(k)){observed="";albumFor="";current=null;hide(a);return;}if(!k.equals(observed)){observed=k;albumFor="";current=null;hide(a);int g=GEN.incrementAndGet();MAIN.postDelayed(()->{Snap n=snap();if(g==GEN.get()&&k.equals(key(n)))detect(a,n,false);},700);}else if(current!=null&&k.equals(albumFor))showCard(a,current,s);}
    private static void detect(Activity a,Snap s,boolean manual){String k=key(s);if(TextUtils.isEmpty(k))return;int g=GEN.incrementAndGet();DETECT.execute(()->{AudifyInstantAlbumMetadata.Album album=null;try{album=AudifyInstantAlbumMetadata.cached(a.getApplicationContext(),k);if(album==null){album=AudifyInstantAlbumMetadata.identify(s.title,s.artist);if(album!=null)AudifyInstantAlbumMetadata.cache(a.getApplicationContext(),k,album);}}catch(Throwable ignored){}AudifyInstantAlbumMetadata.Album out=album;MAIN.post(()->{Activity x=active.get();if(x==null||x.isFinishing()||!k.equals(key(snap())))return;if(!manual&&g!=GEN.get())return;if(out!=null&&out.tracks.size()>1){current=out;albumFor=k;Snap now=snap();showCard(x,out,now);AudifyInstantAlbumResolver.ensure(x.getApplicationContext(),out,now.id,now.title,now.artist,now.thumb);if(manual)showAlbum(x,out,now);}else if(manual)Toast.makeText(x,"Aucun album fiable trouvé pour ce morceau.",Toast.LENGTH_SHORT).show();});});}
    private static void showCard(Activity a,AudifyInstantAlbumMetadata.Album album,Snap s){View c=a.findViewById(android.R.id.content);if(!(c instanceof ViewGroup))return;View p=((ViewGroup)c).findViewWithTag(PILL);if(!(p instanceof ViewGroup))return;View l=((ViewGroup)p).findViewWithTag(LABEL);if(l instanceof TextView)((TextView)l).setText(album.title);View art=((ViewGroup)p).findViewWithTag(COVER);if(art instanceof ImageView)AudifyInstantAlbumArtwork.load(a,album,(ImageView)art,s.thumb);if(p.getVisibility()!=View.VISIBLE){p.setVisibility(View.VISIBLE);p.setAlpha(0);p.animate().alpha(1).setDuration(220).start();}}
    private static void hide(Activity a){View c=a.findViewById(android.R.id.content);if(!(c instanceof ViewGroup))return;View p=((ViewGroup)c).findViewWithTag(PILL);if(p!=null&&p.getVisibility()==View.VISIBLE)p.animate().alpha(0).setDuration(140).withEndAction(()->p.setVisibility(View.GONE)).start();}
    private static void showAlbum(Activity a,AudifyInstantAlbumMetadata.Album album,Snap s){Dialog d=new Dialog(a);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout panel=new LinearLayout(a);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(a,20),dp(a,18),dp(a,20),dp(a,18));GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(20,26,35),Color.rgb(8,11,17)});bg.setCornerRadius(dp(a,28));bg.setStroke(dp(a,1),Color.argb(175,168,255,63));panel.setBackground(bg);
        LinearLayout hero=new LinearLayout(a);hero.setGravity(Gravity.CENTER_VERTICAL);ImageView art=new ImageView(a);art.setScaleType(ImageView.ScaleType.CENTER_CROP);GradientDrawable ab=new GradientDrawable();ab.setColor(Color.rgb(27,34,44));ab.setCornerRadius(dp(a,16));art.setBackground(ab);hero.addView(art,new LinearLayout.LayoutParams(dp(a,92),dp(a,92)));AudifyInstantAlbumArtwork.load(a,album,art,s.thumb);LinearLayout ht=new LinearLayout(a);ht.setOrientation(LinearLayout.VERTICAL);TextView title=text(a,album.title,25,Color.WHITE,true);ht.addView(title,full());String meta=TextUtils.isEmpty(album.artist)?"Artiste inconnu":album.artist;if(!TextUtils.isEmpty(album.date)&&album.date.length()>=4)meta+=" · "+album.date.substring(0,4);meta+=" · "+album.tracks.size()+" titres";TextView artist=text(a,meta,13.5f,Color.rgb(174,184,200),false);LinearLayout.LayoutParams ap=full();ap.topMargin=dp(a,6);ht.addView(artist,ap);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(0,-2,1);hp.leftMargin=dp(a,15);hero.addView(ht,hp);panel.addView(hero,full());
        ScrollView sc=new ScrollView(a);LinearLayout list=new LinearLayout(a);list.setOrientation(LinearLayout.VERTICAL);for(int i=0;i<album.tracks.size();i++){AudifyInstantAlbumMetadata.Track t=album.tracks.get(i);boolean now=i==album.current||AudifyInstantAlbumMetadata.similarity(s.title,t.title)>=2;String line=t.position+".  "+t.title;if(!TextUtils.isEmpty(t.artist)&&!AudifyInstantAlbumMetadata.norm(t.artist).equals(AudifyInstantAlbumMetadata.norm(album.artist)))line+="\n     "+t.artist;TextView row=text(a,line,14,now?Color.rgb(190,255,113):Color.rgb(232,236,242),now);row.setPadding(dp(a,9),dp(a,8),dp(a,9),dp(a,8));if(now){GradientDrawable rb=new GradientDrawable();rb.setColor(Color.argb(43,168,255,63));rb.setCornerRadius(dp(a,12));row.setBackground(rb);}list.addView(row,full());}sc.addView(list,new ScrollView.LayoutParams(-1,-2));LinearLayout.LayoutParams sl=new LinearLayout.LayoutParams(-1,dp(a,270));sl.topMargin=dp(a,14);panel.addView(sc,sl);
        String saved=AudifyInstantAlbumLibrary.find(a,album);TextView save=text(a,TextUtils.isEmpty(saved)?"＋ Enregistrer dans mes playlists":"✓ Album enregistré · Ouvrir",14,Color.rgb(200,255,155),true);save.setGravity(Gravity.CENTER);save.setPadding(dp(a,10),dp(a,12),dp(a,10),dp(a,12));GradientDrawable sb=new GradientDrawable();sb.setColor(Color.argb(46,168,255,63));sb.setCornerRadius(dp(a,18));sb.setStroke(dp(a,1),Color.argb(140,168,255,63));save.setBackground(sb);LinearLayout.LayoutParams sp=full();sp.topMargin=dp(a,12);panel.addView(save,sp);
        TextView play=text(a,"▶  Écouter",15.5f,Color.rgb(7,14,8),true);play.setGravity(Gravity.CENTER);play.setPadding(dp(a,12),dp(a,14),dp(a,12),dp(a,14));GradientDrawable pb=new GradientDrawable();pb.setColor(Color.rgb(168,255,63));pb.setCornerRadius(dp(a,22));play.setBackground(pb);LinearLayout.LayoutParams pp=full();pp.topMargin=dp(a,10);panel.addView(play,pp);
        play.setOnClickListener(v->play(a,album,s,play,d));save.setOnClickListener(v->{String n=AudifyInstantAlbumLibrary.find(a,album);if(!TextUtils.isEmpty(n))AudifyInstantAlbumLibrary.open(a,n,d);else save(a,album,s,save,d);});d.setContentView(panel);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);WindowManager.LayoutParams p=new WindowManager.LayoutParams();p.copyFrom(w.getAttributes());p.width=Math.min(a.getResources().getDisplayMetrics().widthPixels-dp(a,24),dp(a,470));p.height=-2;p.gravity=Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL;p.dimAmount=.72f;p.y=dp(a,12);w.setAttributes(p);}d.show();}
    private static void play(Activity a,AudifyInstantAlbumMetadata.Album album,Snap s,TextView b,Dialog d){b.setEnabled(false);b.setAlpha(.82f);b.setText("Préparation…");AudifyInstantAlbumResolver.State st=AudifyInstantAlbumResolver.ensure(a,album,s.id,s.title,s.artist,s.thumb);long start=android.os.SystemClock.elapsedRealtime();MAIN.post(new Runnable(){public void run(){if(a.isFinishing()||!d.isShowing())return;AudifyInstantAlbumResolver.Playable first=st.get(0);if(first!=null){try{ArrayList<AudifyInstantAlbumResolver.Playable> q=st.ready();AudifyInstantAlbumResolver.launch(a,q);st.markPlaying();d.dismiss();}catch(Throwable e){b.setEnabled(true);b.setAlpha(1);b.setText("▶  Réessayer");}return;}if(st.complete||android.os.SystemClock.elapsedRealtime()-start>18000){b.setEnabled(true);b.setAlpha(1);b.setText("▶  Réessayer");Toast.makeText(a,"Le premier titre n’a pas pu être préparé.",Toast.LENGTH_SHORT).show();return;}MAIN.postDelayed(this,100);}});}
    private static void save(Activity a,AudifyInstantAlbumMetadata.Album album,Snap s,TextView b,Dialog d){b.setEnabled(false);b.setText("Préparation…");AudifyInstantAlbumResolver.State st=AudifyInstantAlbumResolver.ensure(a,album,s.id,s.title,s.artist,s.thumb);long start=android.os.SystemClock.elapsedRealtime();MAIN.post(new Runnable(){public void run(){if(a.isFinishing()||!d.isShowing())return;if(st.complete||android.os.SystemClock.elapsedRealtime()-start>22000){ArrayList<AudifyInstantAlbumResolver.Playable> q=st.ready();if(q.isEmpty()){b.setEnabled(true);b.setText("＋ Enregistrer dans mes playlists");return;}Runnable go=()->{try{AudifyInstantAlbumLibrary.save(a,album,q);b.setEnabled(true);b.setText("✓ Album enregistré · Ouvrir");Toast.makeText(a,"Album enregistré",Toast.LENGTH_SHORT).show();}catch(Throwable e){b.setEnabled(true);b.setText("＋ Enregistrer dans mes playlists");Toast.makeText(a,"Impossible d’enregistrer l’album.",Toast.LENGTH_SHORT).show();}};if(q.size()<album.tracks.size())new AlertDialog.Builder(a).setTitle("Album partiellement retrouvé").setMessage(q.size()+" titres sur "+album.tracks.size()+" ont été retrouvés. Enregistrer ces titres dans leur ordre d’origine ?").setPositiveButton("Enregistrer",(x,y)->go.run()).setNegativeButton("Annuler",(x,y)->{b.setEnabled(true);b.setText("＋ Enregistrer dans mes playlists");}).show();else go.run();return;}MAIN.postDelayed(this,180);}});}
    private static Snap snap(){Snap s=new Snap();try{Class<?> c=Class.forName(SERVICE);s.id=stat(c,"snapshotVideoId");s.title=stat(c,"snapshotTitle");s.artist=stat(c,"snapshotArtist");s.thumb=stat(c,"snapshotThumbnail");}catch(Throwable ignored){}return s;}
    private static String stat(Class<?> c,String n){try{Field f=c.getDeclaredField(n);f.setAccessible(true);Object v=f.get(null);return v==null?"":String.valueOf(v);}catch(Throwable e){return "";}}
    private static String key(Snap s){if(s==null||TextUtils.isEmpty(s.title))return "";return (TextUtils.isEmpty(s.id)?"":s.id+"|")+AudifyInstantAlbumMetadata.norm(s.title)+"|"+AudifyInstantAlbumMetadata.norm(s.artist);}
    private static TextView text(Activity a,String s,float z,int c,boolean bold){TextView v=new TextView(a);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}
    private static LinearLayout.LayoutParams full(){return new LinearLayout.LayoutParams(-1,-2);}
    private static int dp(Context c,int x){return Math.round(x*c.getResources().getDisplayMetrics().density);}
    private static final class DiscButton extends View {final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);DiscButton(Context c){super(c);}@Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(2,w*.055f));p.setColor(Color.rgb(168,255,63));c.drawCircle(w/2,h/2,w*.27f,p);c.drawCircle(w/2,h/2,w*.09f,p);p.setStyle(Paint.Style.FILL);c.drawCircle(w/2,h/2,w*.035f,p);}}
}
