(()=>{'use strict';
const API='https://api.audius.co/v1',DISCOVERY='https://discoveryprovider.audius.co/v1',APP='Audify',K={fav:'audify_favorites_v2',hist:'audify_history_v2',queue:'audify_queue_v2'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const get=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
let items=[],idx=-1,cur=null,currentTab='home',queue=get(K.queue),loop=false,playerOpen=false;
let sourceList=[],sourceIndex=-1,sourceToken=0,sourceTimer=0;
const audio=$('#audio');
const say=t=>{let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>e.classList.remove('show'),2200)};
const isHttp=v=>typeof v==='string'&&/^https?:\/\//i.test(v);
const streamUrl=(base,id)=>`${base}/tracks/${encodeURIComponent(id)}/stream?app_name=${encodeURIComponent(APP)}`;
function norm(x){let id=String(x?.id||'');return{id,title:x?.title||'Sans titre',artist:x?.user?.name||x?.artist||'Audius',thumbnail:x?.artwork?._1000x1000||x?.artwork?._480x480||x?.artwork?._150x150||x?.thumbnail||'',stream:isHttp(x?.stream)?x.stream:'',isStreamable:x?.is_streamable??x?.isStreamable??true,isStreamGated:!!(x?.is_stream_gated??x?.isStreamGated)}}
function playable(x){let v=x?.is_streamable??x?.isStreamable;if(v===false||String(v).toLowerCase()==='false')return false;if(x?.is_stream_gated===true||x?.isStreamGated===true)return false;return true}
function sourcesFor(t){let out=[];if(isHttp(t?.stream))out.push(t.stream);out.push(streamUrl(DISCOVERY,t.id),streamUrl(API,t.id));return [...new Set(out)]}
function isFav(id){return get(K.fav).some(x=>x.id===id)}
function addHistory(t){let a=get(K.hist).filter(x=>x.id!==t.id);a.unshift({...t,at:Date.now()});set(K.hist,a.slice(0,100))}
function syncLike(){if(!cur)return;let on=isFav(cur.id);['#likeTop','#likeMain'].forEach(sel=>{let b=$(sel);b.textContent=on?'♥':'♡';b.classList.toggle('active',on)})}
function toggleFav(t,rerender=true){let a=get(K.fav),i=a.findIndex(x=>x.id===t.id);i>=0?a.splice(i,1):a.unshift(t);set(K.fav,a.slice(0,200));say(i>=0?'Retiré des favoris':'Ajouté aux favoris');syncLike();if(rerender&&!playerOpen)renderTab()}
function addQueue(t){if(!t)return;let exists=queue.some(x=>x.id===t.id);if(!exists){queue.push(norm(t));set(K.queue,queue)}say(exists?'Déjà dans la playlist':'Ajouté à la playlist')}
function cards(a){if(!a.length)return'<div class="empty">Aucun morceau lisible ici pour le moment.</div>';return`<div class="grid">${a.map((t,i)=>`<article class="card"><button class="coverBtn" data-open="${i}" aria-label="Ouvrir ${esc(t.title)}">${t.thumbnail?`<img src="${esc(t.thumbnail)}" alt="" loading="lazy">`:'<div class="cover-fallback">♫</div>'}</button><b>${esc(t.title)}</b><span>${esc(t.artist)}</span><div class="row"><button class="play" data-play="${i}">▶ Lire</button><button data-fav="${i}">${isFav(t.id)?'♥':'♡'}</button></div></article>`).join('')}</div>`}
function bind(a){$$('[data-open]').forEach(b=>b.onclick=()=>{items=a;play(a[+b.dataset.open],+b.dataset.open,true)});$$('[data-play]').forEach(b=>b.onclick=()=>{items=a;play(a[+b.dataset.play],+b.dataset.play,true)});$$('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(a[+b.dataset.fav]))}
function renderTab(){let c=$('#content'),a;if(currentTab==='fav'){a=get(K.fav);c.className='';c.innerHTML='<div class="section-title"><h2>Favoris</h2><span>'+a.length+'</span></div>'+cards(a);bind(a)}else if(currentTab==='history'){a=get(K.hist);c.className='';c.innerHTML='<div class="section-title"><h2>Historique</h2><button id="clearHist" class="primary">Effacer</button></div>'+cards(a);bind(a);$('#clearHist')?.addEventListener('click',()=>{set(K.hist,[]);renderTab()})}else if(currentTab==='queue'){queue=get(K.queue);c.className='';c.innerHTML='<div class="section-title"><h2>Playlist</h2><span>'+queue.length+'</span></div>'+(queue.length?'<div class="queue">'+queue.map((t,i)=>`<div class="line">${t.thumbnail?`<img src="${esc(t.thumbnail)}" alt="">`:'<div style="width:48px;height:48px;border-radius:10px;background:#ffffff0d;display:grid;place-items:center">♫</div>'}<div><b>${esc(t.title)}</b><span>${esc(t.artist)}</span></div><button data-q="${i}">▶</button></div>`).join('')+'</div>':'<div class="empty">Ta playlist est vide.</div>');$$('[data-q]').forEach(b=>b.onclick=()=>{items=queue;play(queue[+b.dataset.q],+b.dataset.q,true)})}else{c.className='empty';c.textContent='Recherche une musique pour commencer.'}}
async function search(){let q=$('#q').value.trim();if(!q)return;currentTab='home';$$('[data-tab]').forEach(x=>x.classList.toggle('on',x.dataset.tab==='home'));let c=$('#content');c.className='empty';c.textContent='Recherche…';try{let u=`${API}/tracks/search?query=${encodeURIComponent(q)}&limit=32&app_name=${encodeURIComponent(APP)}`,r=await fetch(u,{headers:{accept:'application/json'}}),j=await r.json();if(!r.ok)throw Error('Erreur de recherche '+r.status);items=(j.data||[]).filter(playable).map(norm).filter(x=>x.id).slice(0,24);c.className='';c.innerHTML=cards(items);bind(items);if(!items.length){c.className='empty';c.textContent='Aucun résultat lisible trouvé.'}}catch(e){c.className='empty';c.innerHTML='<b>Recherche momentanément indisponible</b><br><br>'+esc(e.message)}}
function setAmbient(url){$('#ambientArt').style.backgroundImage=url?`url("${String(url).replace(/"/g,'')}")`:'none';if(!url){applyAmbient(92,59,37);return}let im=new Image();im.crossOrigin='anonymous';im.decoding='async';im.onload=()=>{try{let c=document.createElement('canvas'),ctx=c.getContext('2d',{willReadFrequently:true});c.width=c.height=36;ctx.drawImage(im,0,0,36,36);let d=ctx.getImageData(0,0,36,36).data,r=0,g=0,b=0,n=0;for(let i=0;i<d.length;i+=16){let rr=d[i],gg=d[i+1],bb=d[i+2],mx=Math.max(rr,gg,bb),mn=Math.min(rr,gg,bb);if(mx<35||mn>235)continue;let sat=mx-mn;if(sat<12&&mx>170)continue;r+=rr;g+=gg;b+=bb;n++}if(!n)throw Error('no color');r=Math.round(r/n);g=Math.round(g/n);b=Math.round(b/n);let lum=.2126*r+.7152*g+.0722*b,scale=lum>150?.68:lum<55?1.45:1;r=Math.min(210,Math.round(r*scale));g=Math.min(190,Math.round(g*scale));b=Math.min(190,Math.round(b*scale));applyAmbient(r,g,b)}catch{applyAmbient(92,59,37)}};im.onerror=()=>applyAmbient(92,59,37);im.src=url}
function applyAmbient(r,g,b){document.documentElement.style.setProperty('--ambient',`rgb(${r},${g},${b})`);document.documentElement.style.setProperty('--ambient-rgb',`${r},${g},${b}`)}
function openPlayer(){if(!cur)return;playerOpen=true;$('#playerScreen').classList.add('open');$('#playerScreen').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closePlayer(){playerOpen=false;$('#playerScreen').classList.remove('open');$('#playerScreen').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function updateBigPlayer(){if(!cur)return;let img=cur.thumbnail||'';$('#bigCover').src=img;$('#bigTitle').textContent=cur.title;$('#bigArtist').textContent=cur.artist;$('#pt').src=img;$('#pn').textContent=cur.title;$('#pa').textContent=cur.artist;$('#miniPlayer').classList.add('show');$('#vinyl').style.setProperty('--vinyl-label',img?`url("${String(img).replace(/"/g,'')}")`:'linear-gradient(145deg,#61432c,#1d1611)');setAmbient(img);syncLike()}
function clearSourceTimer(){clearTimeout(sourceTimer);sourceTimer=0}
function trySource(n,autoplay=true){clearSourceTimer();if(!cur||!sourceList.length)return;sourceIndex=n;if(sourceIndex>=sourceList.length){say('Aucune source audio web disponible pour ce morceau');syncPlayback();return}const token=++sourceToken;try{audio.pause();audio.removeAttribute('src');audio.load()}catch{}audio.src=sourceList[sourceIndex];audio.load();sourceTimer=setTimeout(()=>{if(token!==sourceToken||!audio.paused||audio.readyState>=2)return;trySource(sourceIndex+1,true)},10000);if(autoplay){const p=audio.play();p?.catch(err=>{if(token!==sourceToken)return;if(String(err?.name||'')==='NotAllowedError'){say('Le navigateur attend un clic sur Lecture');return}if(sourceIndex+1<sourceList.length)trySource(sourceIndex+1,true);else say('La source audio de ce morceau est indisponible')})}}
function preparePlayback(t){sourceList=sourcesFor(t);sourceIndex=-1;trySource(0,true)}
function resumePlayback(){if(!cur)return say('Choisis une musique');if(audio.error||!audio.currentSrc){sourceList=sourcesFor(cur);trySource(0,true);return}if(audio.paused)audio.play().catch(err=>{if(String(err?.name||'')==='NotAllowedError')say('Clique encore sur Lecture');else if(sourceIndex+1<sourceList.length)trySource(sourceIndex+1,true);else say('Impossible de lire ce morceau')});else audio.pause()}
function play(t,i=-1,open=true){cur=norm(t);if(i>=0)idx=i;addHistory(cur);updateBigPlayer();preparePlayback(cur);if(open)openPlayer()}
function next(){if(!items.length)return;idx=(idx+1+items.length)%items.length;play(items[idx],idx,playerOpen)}
function prev(){if(!items.length)return;idx=(idx-1+items.length)%items.length;play(items[idx],idx,playerOpen)}
function fmt(sec){if(!Number.isFinite(sec)||sec<0)return'0:00';let m=Math.floor(sec/60),s=Math.floor(sec%60);return`${m}:${String(s).padStart(2,'0')}`}
function syncPlayback(){let paused=audio.paused;$('#toggle').textContent=paused?'▶':'❚❚';$('#playMain').textContent=paused?'▶':'❚❚';$('#vinyl').classList.toggle('spinning',!paused);$('#playMain').setAttribute('aria-label',paused?'Lecture':'Pause')}
$('#go').onclick=search;$('#q').onkeydown=e=>{if(e.key==='Enter')search()};
$('#toggle').onclick=resumePlayback;$('#playMain').onclick=resumePlayback;
$('#next').onclick=next;$('#prev').onclick=prev;$('#miniOpen').onclick=openPlayer;$('#closePlayer').onclick=closePlayer;
$('#likeTop').onclick=()=>cur&&toggleFav(cur,false);$('#likeMain').onclick=()=>cur&&toggleFav(cur,false);
$('#addTop').onclick=()=>addQueue(cur);$('#playlistBtn').onclick=()=>addQueue(cur);
$('#loopBtn').onclick=()=>{loop=!loop;audio.loop=loop;$('#loopBtn').classList.toggle('active',loop);say(loop?'Lecture en boucle activée':'Lecture en boucle désactivée')};
$('#karaokeBtn').onclick=()=>{$('#karaokeBtn').classList.toggle('active');$('#karaokeSheet').classList.toggle('show')};
$('#seek').oninput=e=>{if(!Number.isFinite(audio.duration)||audio.duration<=0)return;audio.currentTime=(+e.target.value/1000)*audio.duration};
audio.onloadedmetadata=()=>{$('#durTime').textContent=fmt(audio.duration)};audio.oncanplay=clearSourceTimer;audio.ontimeupdate=()=>{let p=Number.isFinite(audio.duration)&&audio.duration>0?audio.currentTime/audio.duration:0;$('#curTime').textContent=fmt(audio.currentTime);$('#durTime').textContent=fmt(audio.duration);$('#seek').value=Math.round(p*1000);$('#seek').style.setProperty('--seek',`${(p*100).toFixed(2)}%`)};
audio.onplay=()=>{clearSourceTimer();syncPlayback()};audio.onpause=syncPlayback;audio.onended=()=>{if(!loop)next()};audio.onerror=()=>{clearSourceTimer();if(cur&&sourceIndex+1<sourceList.length)trySource(sourceIndex+1,true);else{say('Ce titre ne peut pas être lu avec une source web disponible');syncPlayback()}};
$$('[data-tab]').forEach(b=>b.onclick=()=>{currentTab=b.dataset.tab;$$('[data-tab]').forEach(x=>x.classList.toggle('on',x===b));renderTab()});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&playerOpen)closePlayer();if(e.code==='Space'&&playerOpen&&!/INPUT|TEXTAREA/.test(document.activeElement?.tagName)){e.preventDefault();resumePlayback()}});
window.AudifyWebInfo={release:'70.4.2',platform:'web',hosted:true,search:'Audius',player:'immersive-v2',audioEngine:'Audius Web MP3 fallback'};
})();