(()=>{'use strict';
const YT_API='https://www.googleapis.com/youtube/v3/search';
const YT_KEY='AIzaSyDY2Lz5pnOkpwYuMN03DbkYtU4XJTACcJQ';
const K={fav:'audify_favorites_v2',hist:'audify_history_v2',queue:'audify_queue_v2'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const get=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const decode=s=>{const t=document.createElement('textarea');t.innerHTML=String(s??'');return t.value};
const directId=v=>{const m=String(v).match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|shorts\/|embed\/))([\w-]{11})/);return m?.[1]||(/^[\w-]{11}$/.test(String(v))?String(v):null)};
let items=[],idx=-1,cur=null,currentTab='home',queue=get(K.queue),loop=false,playerOpen=false;
let yt=null,ytReady=false,ytPending=null,ytLoading=false,progressTimer=0;
const say=t=>{const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>e.classList.remove('show'),2200)};
function thumb(id,url=''){return url||`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`}
function norm(x){const id=String(x?.id?.videoId||x?.id||'');const sn=x?.snippet||{};return{source:'youtube',id,title:decode(sn.title||x?.title||'Sans titre'),artist:decode(sn.channelTitle||x?.artist||'YouTube'),thumbnail:thumb(id,sn?.thumbnails?.maxres?.url||sn?.thumbnails?.standard?.url||sn?.thumbnails?.high?.url||sn?.thumbnails?.medium?.url||sn?.thumbnails?.default?.url||x?.thumbnail||'')}}
function isFav(id){return get(K.fav).some(x=>x.id===id)}
function addHistory(t){let a=get(K.hist).filter(x=>x.id!==t.id);a.unshift({...t,at:Date.now()});set(K.hist,a.slice(0,100))}
function syncLike(){if(!cur)return;const on=isFav(cur.id);['#likeTop','#likeMain'].forEach(sel=>{const b=$(sel);if(!b)return;b.textContent=on?'♥':'♡';b.classList.toggle('active',on)})}
function toggleFav(t,rerender=true){let a=get(K.fav),i=a.findIndex(x=>x.id===t.id);i>=0?a.splice(i,1):a.unshift(norm(t));set(K.fav,a.slice(0,200));say(i>=0?'Retiré des favoris':'Ajouté aux favoris');syncLike();if(rerender&&!playerOpen)renderTab()}
function addQueue(t){if(!t)return;const n=norm(t),exists=queue.some(x=>x.id===n.id);if(!exists){queue.push(n);set(K.queue,queue)}say(exists?'Déjà dans la playlist':'Ajouté à la playlist')}
function imgMarkup(t){const u=esc(thumb(t.id,t.thumbnail));const fb=esc(`https://i.ytimg.com/vi/${t.id}/mqdefault.jpg`);return `<img src="${u}" alt="${esc(t.title)}" referrerpolicy="no-referrer" loading="lazy" onerror="this.onerror=null;this.src='${fb}'">`}
function cards(a){if(!a.length)return'<div class="empty">Aucun morceau ici pour le moment.</div>';return`<div class="grid">${a.map((t,i)=>`<article class="card"><button class="coverBtn" data-open="${i}" aria-label="Ouvrir ${esc(t.title)}">${imgMarkup(t)}</button><b>${esc(t.title)}</b><span>${esc(t.artist)}</span><div class="row"><button class="play" data-play="${i}">▶ Lire</button><button data-fav="${i}">${isFav(t.id)?'♥':'♡'}</button></div></article>`).join('')}</div>`}
function bind(a){$$('[data-open]').forEach(b=>b.onclick=()=>{items=a;play(a[+b.dataset.open],+b.dataset.open,true)});$$('[data-play]').forEach(b=>b.onclick=()=>{items=a;play(a[+b.dataset.play],+b.dataset.play,true)});$$('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(a[+b.dataset.fav]))}
function renderTab(){const c=$('#content');let a;if(currentTab==='fav'){a=get(K.fav).map(norm);c.className='';c.innerHTML='<div class="section-title"><h2>Favoris</h2><span>'+a.length+'</span></div>'+cards(a);bind(a)}else if(currentTab==='history'){a=get(K.hist).map(norm);c.className='';c.innerHTML='<div class="section-title"><h2>Historique</h2><button id="clearHist" class="primary">Effacer</button></div>'+cards(a);bind(a);$('#clearHist')?.addEventListener('click',()=>{set(K.hist,[]);renderTab()})}else if(currentTab==='queue'){queue=get(K.queue).map(norm);c.className='';c.innerHTML='<div class="section-title"><h2>Playlist</h2><span>'+queue.length+'</span></div>'+(queue.length?'<div class="queue">'+queue.map((t,i)=>`<div class="line">${imgMarkup(t)}<div><b>${esc(t.title)}</b><span>${esc(t.artist)}</span></div><button data-q="${i}">▶</button></div>`).join('')+'</div>':'<div class="empty">Ta playlist est vide.</div>');$$('[data-q]').forEach(b=>b.onclick=()=>{items=queue;play(queue[+b.dataset.q],+b.dataset.q,true)})}else{c.className='empty';c.textContent='Recherche une musique YouTube pour commencer.'}}
async function search(){const q=$('#q').value.trim();if(!q)return;currentTab='home';$$('[data-tab]').forEach(x=>x.classList.toggle('on',x.dataset.tab==='home'));const c=$('#content');c.className='empty';c.textContent='Recherche YouTube…';const id=directId(q);if(id){items=[norm({id,title:'Vidéo YouTube',artist:'YouTube',thumbnail:thumb(id)})];c.className='';c.innerHTML=cards(items);bind(items);return}try{const u=new URL(YT_API);for(const [k,v] of Object.entries({part:'snippet',type:'video',videoEmbeddable:'true',maxResults:'24',order:'relevance',q,key:YT_KEY}))u.searchParams.set(k,v);const r=await fetch(u,{headers:{accept:'application/json'}});const j=await r.json();if(!r.ok)throw Error(j?.error?.message||`YouTube API HTTP ${r.status}`);items=(j.items||[]).map(norm).filter(x=>x.id);c.className='';c.innerHTML=cards(items);bind(items);if(!items.length){c.className='empty';c.textContent='Aucun résultat YouTube trouvé.'}}catch(e){c.className='empty';c.innerHTML='<b>Recherche YouTube indisponible</b><br><br>'+esc(e?.message||String(e))}}
function setAmbient(url,seed){$('#ambientArt').style.backgroundImage=url?`url("${String(url).replace(/"/g,'')}")`:'none';const fallback=()=>{let h=0;for(const ch of String(seed||''))h=(h*31+ch.charCodeAt(0))>>>0;const hue=h%360;applyAmbientHsl(hue)};if(!url)return fallback();const im=new Image();im.crossOrigin='anonymous';im.referrerPolicy='no-referrer';im.onload=()=>{try{const c=document.createElement('canvas'),ctx=c.getContext('2d',{willReadFrequently:true});c.width=c.height=32;ctx.drawImage(im,0,0,32,32);const d=ctx.getImageData(0,0,32,32).data;let r=0,g=0,b=0,n=0;for(let i=0;i<d.length;i+=16){const rr=d[i],gg=d[i+1],bb=d[i+2],mx=Math.max(rr,gg,bb),mn=Math.min(rr,gg,bb);if(mx<30||mn>235||mx-mn<12)continue;r+=rr;g+=gg;b+=bb;n++}if(!n)return fallback();r=Math.round(r/n*.72);g=Math.round(g/n*.72);b=Math.round(b/n*.72);applyAmbient(Math.min(190,r),Math.min(190,g),Math.min(190,b))}catch{fallback()}};im.onerror=fallback;im.src=url}
function applyAmbient(r,g,b){document.documentElement.style.setProperty('--ambient-rgb',`${r},${g},${b}`)}
function applyAmbientHsl(h){const c=document.createElement('canvas').getContext('2d');c.fillStyle=`hsl(${h} 38% 28%)`;c.fillRect(0,0,1,1);const d=c.getImageData(0,0,1,1).data;applyAmbient(d[0],d[1],d[2])}
function openPlayer(){if(!cur)return;playerOpen=true;$('#playerScreen').classList.add('open');$('#playerScreen').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';ensureYTDock()}
function closePlayer(){playerOpen=false;$('#playerScreen').classList.remove('open');$('#playerScreen').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function updateBigPlayer(){if(!cur)return;const img=thumb(cur.id,cur.thumbnail);$('#bigCover').src=img;$('#bigCover').referrerPolicy='no-referrer';$('#bigCover').onerror=()=>{$('#bigCover').onerror=null;$('#bigCover').src=`https://i.ytimg.com/vi/${cur.id}/mqdefault.jpg`};$('#bigTitle').textContent=cur.title;$('#bigArtist').textContent=cur.artist;$('#pt').src=img;$('#pt').referrerPolicy='no-referrer';$('#pn').textContent=cur.title;$('#pa').textContent=cur.artist;$('#miniPlayer').classList.add('show');$('#vinyl').style.setProperty('--vinyl-label',`url("${img.replace(/"/g,'')}")`);setAmbient(img,cur.id);syncLike();setMediaSession()}
function ensureYTDock(){if($('#ytDock'))return;const st=document.createElement('style');st.textContent='.yt-dock{max-width:820px;margin:16px auto 0;padding:12px;border:1px solid #ffffff20;border-radius:26px;background:#0b0b0bd9;display:none;align-items:center;gap:16px}.yt-dock.show{display:flex}.yt-frame{width:220px;height:220px;min-width:220px;overflow:hidden;border-radius:18px;background:#000}.yt-frame iframe{width:220px!important;height:220px!important;border:0}.yt-copy{min-width:0}.yt-copy b{display:block;font-size:16px;margin-bottom:5px}.yt-copy span{display:block;color:#aaa;font-size:12px;line-height:1.45}@media(max-width:640px){.yt-dock{flex-direction:column}.yt-frame,.yt-frame iframe{width:220px!important;height:220px!important}}';document.head.appendChild(st);const d=document.createElement('section');d.id='ytDock';d.className='yt-dock';d.innerHTML='<div class="yt-frame"><div id="ytEngine"></div></div><div class="yt-copy"><b>Source YouTube</b><span>Le catalogue et la lecture proviennent de YouTube. La vidéo officielle reste visible ici pendant la lecture.</span></div>';document.querySelector('.control-panel')?.insertAdjacentElement('afterend',d)}
function ensureYT(){ensureYTDock();if(window.YT?.Player){initYT();return}if(ytLoading)return;ytLoading=true;const old=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{try{old?.()}catch{}initYT()};const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.async=true;s.onerror=()=>say('Le lecteur YouTube ne peut pas être chargé');document.head.appendChild(s)}
function initYT(){if(yt||!window.YT?.Player)return;yt=new YT.Player('ytEngine',{width:220,height:220,playerVars:{playsinline:1,controls:1,rel:0,fs:1,enablejsapi:1,origin:location.origin},events:{onReady:()=>{ytReady=true;$('#ytDock')?.classList.add('show');if(ytPending){const p=ytPending;ytPending=null;loadYT(p)}},onStateChange:onYTState,onError:e=>{say(`YouTube ne peut pas lire ce titre (${e.data})`);syncPlayback()},onAutoplayBlocked:()=>say('Le navigateur a bloqué le démarrage automatique : clique sur Lecture')}})}
function loadYT(t){ensureYT();ytPending=t;if(!ytReady||!yt)return;ytPending=null;$('#ytDock')?.classList.add('show');try{yt.loadVideoById(t.id)}catch{say('Impossible de charger ce titre YouTube')}}
function play(t,i=-1,open=true){cur=norm(t);if(i>=0)idx=i;addHistory(cur);updateBigPlayer();if(open)openPlayer();loadYT(cur)}
function next(){if(!items.length)return;idx=(idx+1+items.length)%items.length;play(items[idx],idx,playerOpen)}
function prev(){if(!items.length)return;idx=(idx-1+items.length)%items.length;play(items[idx],idx,playerOpen)}
function resumePlayback(){if(!cur)return say('Choisis une musique');ensureYT();if(!ytReady||!yt){ytPending=cur;return say('Chargement du lecteur YouTube…')}const s=yt.getPlayerState();s===YT.PlayerState.PLAYING?yt.pauseVideo():yt.playVideo()}
function fmt(sec){sec=Math.max(0,Math.floor(Number(sec)||0));return`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function syncPlayback(force){const playing=force??(ytReady&&yt&&yt.getPlayerState()===YT.PlayerState.PLAYING);$('#toggle').textContent=playing?'❚❚':'▶';$('#playMain').textContent=playing?'❚❚':'▶';$('#vinyl').classList.toggle('spinning',!!playing)}
function onYTState(e){if(e.data===YT.PlayerState.PLAYING)syncPlayback(true);else if(e.data===YT.PlayerState.PAUSED||e.data===YT.PlayerState.CUED||e.data===YT.PlayerState.ENDED)syncPlayback(false);if(e.data===YT.PlayerState.ENDED){if(loop)yt.seekTo(0,true),yt.playVideo();else next()}}
function tick(){if(!ytReady||!yt||!cur)return;try{const d=yt.getDuration()||0,c=yt.getCurrentTime()||0,p=d?c/d:0;$('#curTime').textContent=fmt(c);$('#durTime').textContent=fmt(d);$('#seek').value=Math.round(p*1000);$('#seek').style.setProperty('--seek',`${(p*100).toFixed(2)}%`)}catch{}}
function setMediaSession(){if(!cur||!('mediaSession'in navigator)||typeof MediaMetadata==='undefined')return;try{navigator.mediaSession.metadata=new MediaMetadata({title:cur.title,artist:cur.artist,album:'Audify • YouTube',artwork:cur.thumbnail?[{src:cur.thumbnail}]:[]});navigator.mediaSession.setActionHandler('play',()=>yt?.playVideo());navigator.mediaSession.setActionHandler('pause',()=>yt?.pauseVideo());navigator.mediaSession.setActionHandler('nexttrack',next);navigator.mediaSession.setActionHandler('previoustrack',prev)}catch{}}
$('#go').onclick=search;$('#q').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();search()}};
$('#toggle').onclick=resumePlayback;$('#playMain').onclick=resumePlayback;$('#next').onclick=next;$('#prev').onclick=prev;$('#miniOpen').onclick=openPlayer;$('#closePlayer').onclick=closePlayer;
$('#likeTop').onclick=()=>cur&&toggleFav(cur,false);$('#likeMain').onclick=()=>cur&&toggleFav(cur,false);$('#addTop').onclick=()=>addQueue(cur);$('#playlistBtn').onclick=()=>addQueue(cur);
$('#loopBtn').onclick=()=>{loop=!loop;$('#loopBtn').classList.toggle('active',loop);say(loop?'Lecture en boucle activée':'Lecture en boucle désactivée')};
$('#karaokeBtn').onclick=()=>{$('#karaokeBtn').classList.toggle('active');$('#karaokeSheet').classList.toggle('show')};
$('#seek').oninput=e=>{if(!ytReady||!yt)return;const d=yt.getDuration()||0;if(d)yt.seekTo((+e.target.value/1000)*d,true)};
$$('[data-tab]').forEach(b=>b.onclick=()=>{currentTab=b.dataset.tab;$$('[data-tab]').forEach(x=>x.classList.toggle('on',x===b));renderTab()});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&playerOpen)closePlayer();if(e.code==='Space'&&playerOpen&&!/INPUT|TEXTAREA/.test(document.activeElement?.tagName)){e.preventDefault();resumePlayback()}});
progressTimer=setInterval(tick,350);ensureYT();
window.AudifyWebInfo={release:'70.4.2',platform:'web',hosted:true,catalogue:'YouTube',player:'YouTube IFrame API',thumbnails:'YouTube'};
})();