import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const output=await mkdtemp(path.join(tmpdir(),'audify-startup-tests-'));
const javaBin=process.env.AUDIFY_JAVA_BIN||'';
execFileSync(javaBin?path.join(javaBin,'javac'):'javac',['-encoding','UTF-8','-d',output,
 path.join(root,'startup/src/com/nova/audify/AudifyStartupState.java'),path.join(root,'startup/tests/AudifyStartupStateTest.java')],{stdio:'inherit'});
execFileSync(javaBin?path.join(javaBin,'java'):'java',['-cp',output,'com.nova.audify.AudifyStartupStateTest'],{stdio:'inherit'});
const java=path.join(root,'android/app/src/main/java/com/nova/audify');
const home=await readFile(path.join(java,'NativeHomeActivity.java'),'utf8');
const manifest=await readFile(path.join(root,'android/app/src/main/AndroidManifest.xml'),'utf8');
const sync=await readFile(path.join(java,'AudifyFirebaseSync.java'),'utf8');
const service=await readFile(path.join(java,'AudifyPlaybackService.java'),'utf8');
const logo=await readFile(path.join(java,'AudifyChromaLogoView.java'),'utf8');
const library=await readFile(path.join(java,'AudifyLibraryStore.java'),'utf8');
const karaoke=await readFile(path.join(java,'NativeKaraokeActivity.java'),'utf8');
const player=await readFile(path.join(java,'NativePlayerActivity.java'),'utf8');
assert.equal((manifest.match(/android.intent.category.LAUNCHER/g)||[]).length,1,'one launcher');
assert.ok(!manifest.includes('android:name=".AudifySplashActivity"'),'old splash is not a second activity');
assert.equal((home.match(/void onStart\(\)/g)||[]).length,1,'no duplicate lifecycle hooks');
assert.equal((home.match(/void onStop\(\)/g)||[]).length,1);
assert.ok(home.indexOf('SplashScreen.installSplashScreen(this)')<home.indexOf('super.onCreate(savedInstanceState)'),'system splash installed first');
assert.ok(home.includes('startup.mountHome(root)'),'actual home mounted behind overlay');
assert.ok(!home.includes('AudifyMonetizationManager.get(this).isPremium()'),'Billing is not touched while startup paints');
assert.ok(home.includes('startup.assetFinished(recommendationsTicket'),'recommendations have completion callback');
assert.ok(sync.includes('.get(Source.SERVER)'),'fresh server checkpoint');
assert.ok(home.includes('!startup.isRevealed()||libraryContent==null'),'no early Firebase UI refresh');
assert.ok(!home.includes('postDelayed(()->openAudify'),'no fixed readiness timer');
assert.ok(home.includes('showStartupHardFallbackV681242'),'launcher has a platform-only hard fallback');
assert.ok(home.includes('try{AudifyFirebaseAvatar.get(this).removeListener'),'destroy path cannot throw from avatar init');
assert.ok(sync.includes('firebaseAvailableV681242'),'Firebase init has a local guest fallback');
assert.ok(service.includes('new Intent(this, NativeHomeActivity.class)'),'media notification opens native Home');
assert.ok(service.includes('onCreateV681242Guarded'),'media service creation is guarded');
assert.ok(logo.includes('setLayerType(View.LAYER_TYPE_HARDWARE,null);'),'chroma renderer preserves alpha masking');
assert.ok(library.includes('getLikesForStartupV681242'),'startup Home data is bounded');
assert.ok(karaoke.includes('showKaraokeHardFallbackV681243'),'karaoke launch has a safe fallback');
assert.ok(karaoke.includes('postKaraokeUiV681243'),'lyrics callbacks respect activity lifecycle');
assert.ok(player.includes('hydrateCurrentTrackV681243'),'karaoke button recovers the active player track');
console.log('Audify startup: 20 generated integration checks passed');
